/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVue;

import java.awt.Container;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import pkgEntite.Etablissement;
import pkgEntite.HibernateUtil;

/**
 *
 * @author Kevin
 */
public class JFrameFestival extends javax.swing.JFrame {
    
    // Déclaration d’une session commune aux différentes interfaces
    public static Session session = HibernateUtil.getSessionFactory().openSession();
    private JPanelAccueil pnlAccueil = new JPanelAccueil();
    
    //lier le Panel Etab Liste avec la JFrame
    protected JPanelEtabListe pnlEtabListe = new JPanelEtabListe();
    protected JpanelEtabAjout pnlEtabAjout = new JpanelEtabAjout();
    protected JPanelOffHeber pnlOffHeber = new JPanelOffHeber();
    protected JPanelTypeChListe pnlTypeChListe=new JPanelTypeChListe();
    protected JPanelTypeChAjout pnlAjoutTypeCh=new JPanelTypeChAjout();
    private Container pnlPrinc = null;
    

    /**
     * Creates new form JFrameFestival
     */
    public JFrameFestival() {
        initComponents();
        this.setContentPane(pnlAccueil);
        pack(); //permet de rafraichir
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public static Session getSession() {
        return session;
    }

    public static void setSession(Session session) {
        JFrameFestival.session = session;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnEtablissement = new javax.swing.JMenu();
        jMnListEtab = new javax.swing.JMenuItem();
        jMnAjoutEtab = new javax.swing.JMenuItem();
        jMnTypeCh = new javax.swing.JMenu();
        jMnListTypCh = new javax.swing.JMenuItem();
        jMnAjoutTypCh = new javax.swing.JMenuItem();
        jMnOffHber = new javax.swing.JMenu();
        jMnOffHeber = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMnListAtt = new javax.swing.JMenuItem();
        jMnEffAtt = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Fichier");
        jMenuBar1.add(jMenu1);

        jMnEtablissement.setText("Etablissements");

        jMnListEtab.setText("Liste");
        jMnListEtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnListEtabActionPerformed(evt);
            }
        });
        jMnEtablissement.add(jMnListEtab);

        jMnAjoutEtab.setText("Ajouter");
        jMnAjoutEtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnAjoutEtabActionPerformed(evt);
            }
        });
        jMnEtablissement.add(jMnAjoutEtab);

        jMenuBar1.add(jMnEtablissement);

        jMnTypeCh.setText("Type de chambres");

        jMnListTypCh.setText("Liste");
        jMnListTypCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnListTypChActionPerformed(evt);
            }
        });
        jMnTypeCh.add(jMnListTypCh);

        jMnAjoutTypCh.setText("Ajouter");
        jMnAjoutTypCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnAjoutTypChActionPerformed(evt);
            }
        });
        jMnTypeCh.add(jMnAjoutTypCh);

        jMenuBar1.add(jMnTypeCh);

        jMnOffHber.setText("Offre d'hébergements");

        jMnOffHeber.setText("Offres d'hébergements");
        jMnOffHeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnOffHeberActionPerformed(evt);
            }
        });
        jMnOffHber.add(jMnOffHeber);

        jMenuBar1.add(jMnOffHber);

        jMenu5.setText("Attribution des chambres");

        jMnListAtt.setText("Liste");
        jMnListAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnListAttActionPerformed(evt);
            }
        });
        jMenu5.add(jMnListAtt);

        jMnEffAtt.setText("Effectuer attribution");
        jMenu5.add(jMnEffAtt);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnListTypChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnListTypChActionPerformed
        // TODO add your handling code here:
        
        this.setContentPane(pnlTypeChListe);
        pnlTypeChListe.listTypeCh();
        pack();
    }//GEN-LAST:event_jMnListTypChActionPerformed

    private void jMnListAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnListAttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnListAttActionPerformed

    private void jMnListEtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnListEtabActionPerformed
        // TODO add your handling code here:

        this.setContentPane(pnlEtabListe);
        pnlEtabListe.listeEtablissements();
        pack();
    }//GEN-LAST:event_jMnListEtabActionPerformed

    private void jMnAjoutEtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnAjoutEtabActionPerformed
        // TODO add your handling code here:
        this.setContentPane(pnlEtabAjout);
        pack();
    }//GEN-LAST:event_jMnAjoutEtabActionPerformed

    private void jMnOffHeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnOffHeberActionPerformed
        // TODO add your handling code here:
        this.setContentPane(pnlOffHeber);
        pack();
    }//GEN-LAST:event_jMnOffHeberActionPerformed

    private void jMnAjoutTypChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnAjoutTypChActionPerformed
        // TODO add your handling code here:
        
        this.setContentPane(pnlAjoutTypeCh);
        pack();
    }//GEN-LAST:event_jMnAjoutTypChActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFestival.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFestival.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFestival.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFestival.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameFestival().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnAjoutEtab;
    private javax.swing.JMenuItem jMnAjoutTypCh;
    private javax.swing.JMenuItem jMnEffAtt;
    private javax.swing.JMenu jMnEtablissement;
    private javax.swing.JMenuItem jMnListAtt;
    private javax.swing.JMenuItem jMnListEtab;
    private javax.swing.JMenuItem jMnListTypCh;
    private javax.swing.JMenu jMnOffHber;
    private javax.swing.JMenuItem jMnOffHeber;
    private javax.swing.JMenu jMnTypeCh;
    // End of variables declaration//GEN-END:variables
}
