/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVue;

import javax.swing.JOptionPane;
import org.hibernate.Query;
import org.hibernate.Transaction;
import pkgEntite.Etablissement;
import pkgEntite.Typechambre;

/**
 *
 * @author Olivier
 */
public class JPanelTypeChAjout extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTypeChAjout
     */
    public JPanelTypeChAjout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intitule = new javax.swing.JLabel();
        idIntitule = new javax.swing.JLabel();
        libIntitul = new javax.swing.JLabel();
        buttonValider = new javax.swing.JButton();
        buttonRetour = new javax.swing.JButton();
        txtTypeCh = new javax.swing.JTextField();
        txtLibCh = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 800));

        intitule.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        intitule.setText("Nouveau type de chambre");

        idIntitule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idIntitule.setText("Id :");

        libIntitul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        libIntitul.setText("Libelle : ");

        buttonValider.setText("Valider");
        buttonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValiderActionPerformed(evt);
            }
        });

        buttonRetour.setText("Retour");
        buttonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonValider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRetour))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(libIntitul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLibCh, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(idIntitule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTypeCh, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(intitule, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(253, 253, 253))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(intitule)
                        .addGap(53, 53, 53)
                        .addComponent(idIntitule))
                    .addComponent(txtTypeCh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(libIntitul)
                    .addComponent(txtLibCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonValider)
                    .addComponent(buttonRetour))
                .addGap(283, 283, 283))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValiderActionPerformed
        // TODO add your handling code here:
        byte varTemp = 0;
        Transaction tx = JFrameFestival.getSession().beginTransaction();//recupere la session
         
        String sReq = "from Typechambre where TCh_Id = ?";//requete sql
        Query q = JFrameFestival.getSession().createQuery(sReq);//execute la requete
        q.setParameter(0, txtTypeCh.getText());//recupere la valuer tapée et la met dans la requete
        
        if (q.uniqueResult()==null){
            Typechambre unChambre = new Typechambre(txtTypeCh.getText(), txtLibCh.getText());//crée l'objet
            JFrameFestival.getSession().save(unChambre);//enregistre l'objet
            tx.commit();
            JOptionPane.showMessageDialog(null, "Type de chambre ajouté avec succès");//
        }
        
        txtTypeCh.setText("");//remet les champs a vide
        txtLibCh.setText("");
    }//GEN-LAST:event_buttonValiderActionPerformed

    private void buttonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetourActionPerformed
        txtTypeCh.setText("");
        txtLibCh.setText("");
    }//GEN-LAST:event_buttonRetourActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRetour;
    private javax.swing.JButton buttonValider;
    private javax.swing.JLabel idIntitule;
    private javax.swing.JLabel intitule;
    private javax.swing.JLabel libIntitul;
    private javax.swing.JTextField txtLibCh;
    private javax.swing.JTextField txtTypeCh;
    // End of variables declaration//GEN-END:variables
}
