/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVue;

import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import pkgEntite.Etablissement;
import pkgEntite.Offre;
import pkgEntite.Typechambre;

/**
 *
 * @author Kevin
 */
public class JPanelOffHeber extends javax.swing.JPanel {

    /**
     * Creates new form JPanelOffHeber
     */
    public JPanelOffHeber() {
        initComponents();
       // chargerListeEtablissement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCbOffHeber = new javax.swing.JComboBox();
        jLblTitre1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabOffCh = new javax.swing.JTable();
        txtNbChambres = new javax.swing.JTextField();
        jBtnModifier = new javax.swing.JButton();

        jCbOffHeber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbOffHeberActionPerformed(evt);
            }
        });

        jLblTitre1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLblTitre1.setText("Etablissements");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nombre de chambres");

        jTabOffCh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Types", "Capacité", "Nombre de chambres"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabOffCh);
        jTabOffCh.getColumnModel().getColumn(0).setResizable(false);
        jTabOffCh.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTabOffCh.getColumnModel().getColumn(1).setResizable(false);
        jTabOffCh.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTabOffCh.getColumnModel().getColumn(2).setResizable(false);
        jTabOffCh.getColumnModel().getColumn(2).setPreferredWidth(200);

        jBtnModifier.setText("Modifier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLblTitre1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(txtNbChambres, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jBtnModifier)))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCbOffHeber, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLblTitre1)
                .addGap(21, 21, 21)
                .addComponent(jCbOffHeber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(txtNbChambres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jBtnModifier)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCbOffHeberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbOffHeberActionPerformed
        // TODO add your handling code here: 
        
    }//GEN-LAST:event_jCbOffHeberActionPerformed

    public void chargerListeEtablissement(){
        
        String sQuery ;
        
        sQuery = "from Etablissement";
        JFrameFestival.getSession().beginTransaction();
        Query qm = JFrameFestival.getSession().createQuery(sQuery);
        Iterator etab= qm.iterate();
        while (etab.hasNext()){
            Etablissement unEtablissement = (Etablissement)etab.next();
           jCbOffHeber.addItem(unEtablissement.getEtaNom());
           }
        
        /*
        String sReq = "from Etablissement where id = ?";
        Query q = JFrameFestival.getSession().createQuery(sReq);
        q.setParameter(0, jCbOffHeber.getSelectedItem().toString());
        
        Etablissement unEtalissement2 = (Etablissement)q.uniqueResult();
        System.out.println(unEtalissement2);
        String idEtab = unEtalissement2.getId();
        */
        
        String sReq = "from Etablissement where Eta_Nom = ?";
        Query q = JFrameFestival.getSession().createQuery(sReq);
        q.setParameter(0, jCbOffHeber.getSelectedItem());
        
        Etablissement unEtalissement2 = (Etablissement) q.uniqueResult();
        
        System.out.println(unEtalissement2.getEtaId() + "    " + unEtalissement2.getEtaNom());
        
        chargerTabEtab(unEtalissement2);
        
    }
    
    public void chargerTabEtab(Etablissement pEtab){
        
        /*
        String sReq = "from Etablissement where nom = ?";
        Query q = JFrameFestival.getSession().createQuery(sReq);
        q.setParameter(0, pEtab.getId());
        */
        
        //Etablissement unEtalissement2 = (Etablissement)q.uniqueResult();
        //System.out.println(unEtalissement2.getId());
        String idEtab = pEtab.getEtaId();
        //jCbOffHeber.getSelectedItem().toString();
        
        JFrameFestival.getSession().beginTransaction();
        String sQuery = "from Typechambre";
        Query qTypeCh = JFrameFestival.getSession().createQuery(sQuery);
        
        String sQuery2 = "from Offre where Off_Etablissement ";
        
        //à terminer
        
        Iterator typecha = qTypeCh.iterate();
        while (typecha.hasNext()){
            Typechambre unTypeCh = (Typechambre) typecha.next();
            Offre uneOffre = new Offre();
            ((DefaultTableModel) jTabOffCh.getModel()).addRow(new Object[]
            {unTypeCh.getTchId(), unTypeCh.getTchLibelle()});
           }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnModifier;
    private javax.swing.JComboBox jCbOffHeber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblTitre1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabOffCh;
    private javax.swing.JTextField txtNbChambres;
    // End of variables declaration//GEN-END:variables
}
