/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVue;

import java.util.Iterator;
import org.hibernate.Query;
import pkgEntite.Etablissement;
import pkgEntite.Groupe;

/**
 *
 * @author Olivier
 */
public class JPanelEffAttCham extends javax.swing.JPanel {

    /**
     * Creates new form JPanelEffAttCham
     */
    public JPanelEffAttCham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxListeEtabEff = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxGroupeList = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Effectuer ou modifier les attributions:");

        jLabel2.setText("Selectionnez un établissement:");

        jComboBoxListeEtabEff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListeEtabEffActionPerformed(evt);
            }
        });

        jLabel3.setText("Selectionnez le groupe:");

        jComboBoxGroupeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGroupeListActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBoxListeEtabEff, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 136, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jComboBoxGroupeList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))
                        .add(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel3))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxListeEtabEff, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxGroupeList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(333, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxListeEtabEffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListeEtabEffActionPerformed
   
    }//GEN-LAST:event_jComboBoxListeEtabEffActionPerformed

    private void jComboBoxGroupeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGroupeListActionPerformed
 
    }//GEN-LAST:event_jComboBoxGroupeListActionPerformed
    
     public void chargerListeEtablissement(){    //charge la liste d'établissement dans la liste déroulante
        jComboBoxListeEtabEff.removeAllItems();
        String sQuery ;
        
        sQuery = "from Etablissement";
        Query qm = JFrameFestival.getSession().createQuery(sQuery);
        Iterator etab= qm.iterate();
        while (etab.hasNext()){
            Etablissement unEtablissement = (Etablissement)etab.next();
            jComboBoxListeEtabEff.addItem(unEtablissement.getEtaNom());
        }
        
      chargerListeGroupe();

    }
     
       public void chargerListeGroupe(){    //charge la liste d'établissement dans la liste déroulante
        jComboBoxGroupeList.removeAllItems();
        String sQuery ;
        
        sQuery = "from Groupe";
        Query qm = JFrameFestival.getSession().createQuery(sQuery);
        Iterator grou= qm.iterate();
        while (grou.hasNext()){
            Groupe unGroupe = (Groupe)grou.next();
            jComboBoxGroupeList.addItem(unGroupe.getGpNom());
        }
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxGroupeList;
    private javax.swing.JComboBox jComboBoxListeEtabEff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
