package pkgEntite;
// Generated 24 avr. 2014 14:53:42 by Hibernate Tools 3.2.1.GA



/**
 * Attribution generated by hbm2java
 */
public class Attribution  implements java.io.Serializable {


     private AttributionId id;
     private Offre offre;
     private Groupe groupe;
     private byte attNbchambres;

    public Attribution() {
    }

    public Attribution(AttributionId id, Offre offre, Groupe groupe, byte attNbchambres) {
       this.id = id;
       this.offre = offre;
       this.groupe = groupe;
       this.attNbchambres = attNbchambres;
    }
   
    public AttributionId getId() {
        return this.id;
    }
    
    public void setId(AttributionId id) {
        this.id = id;
    }
    public Offre getOffre() {
        return this.offre;
    }
    
    public void setOffre(Offre offre) {
        this.offre = offre;
    }
    public Groupe getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }
    public byte getAttNbchambres() {
        return this.attNbchambres;
    }
    
    public void setAttNbchambres(byte attNbchambres) {
        this.attNbchambres = attNbchambres;
    }




}


