package pkgEntite;
// Generated 24 avr. 2014 14:53:42 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Groupe generated by hbm2java
 */
public class Groupe  implements java.io.Serializable {


     private String gpId;
     private String gpNom;
     private String gpIdentresp;
     private String gpAdresse;
     private byte gpNbpers;
     private String gpNompays;
     private char gpHebergement;
     private Set attributions = new HashSet(0);

    public Groupe() {
    }

	
    public Groupe(String gpId, String gpNom, byte gpNbpers, String gpNompays, char gpHebergement) {
        this.gpId = gpId;
        this.gpNom = gpNom;
        this.gpNbpers = gpNbpers;
        this.gpNompays = gpNompays;
        this.gpHebergement = gpHebergement;
    }
    public Groupe(String gpId, String gpNom, String gpIdentresp, String gpAdresse, byte gpNbpers, String gpNompays, char gpHebergement, Set attributions) {
       this.gpId = gpId;
       this.gpNom = gpNom;
       this.gpIdentresp = gpIdentresp;
       this.gpAdresse = gpAdresse;
       this.gpNbpers = gpNbpers;
       this.gpNompays = gpNompays;
       this.gpHebergement = gpHebergement;
       this.attributions = attributions;
    }
   
    public String getGpId() {
        return this.gpId;
    }
    
    public void setGpId(String gpId) {
        this.gpId = gpId;
    }
    public String getGpNom() {
        return this.gpNom;
    }
    
    public void setGpNom(String gpNom) {
        this.gpNom = gpNom;
    }
    public String getGpIdentresp() {
        return this.gpIdentresp;
    }
    
    public void setGpIdentresp(String gpIdentresp) {
        this.gpIdentresp = gpIdentresp;
    }
    public String getGpAdresse() {
        return this.gpAdresse;
    }
    
    public void setGpAdresse(String gpAdresse) {
        this.gpAdresse = gpAdresse;
    }
    public byte getGpNbpers() {
        return this.gpNbpers;
    }
    
    public void setGpNbpers(byte gpNbpers) {
        this.gpNbpers = gpNbpers;
    }
    public String getGpNompays() {
        return this.gpNompays;
    }
    
    public void setGpNompays(String gpNompays) {
        this.gpNompays = gpNompays;
    }
    public char getGpHebergement() {
        return this.gpHebergement;
    }
    
    public void setGpHebergement(char gpHebergement) {
        this.gpHebergement = gpHebergement;
    }
    public Set getAttributions() {
        return this.attributions;
    }
    
    public void setAttributions(Set attributions) {
        this.attributions = attributions;
    }




}


